export enum DoctorSpecialty {
  ACUPUNCTURE = "Acupuntura",
  ALLERGY_IMMUNOLOGY = "Alergia e Imunologia",
  ANESTHESIOLOGY = "Anestesiologia",
  ANGIOLOGY = "Angiologia",
  CARDIOLOGY = "Cardiologia",
  CARDIOVASCULAR_SURGERY = "Cirurgia Cardiovascular",
  GENERAL_SURGERY = "Cirurgia Geral",
  HEAD_NECK_SURGERY = "Cirurgia de Cabeça e Pescoço",
  PEDIATRIC_SURGERY = "Cirurgia Pediátrica",
  PLASTIC_SURGERY = "Cirurgia Plástica",
  THORACIC_SURGERY = "Cirurgia Torácica",
  VASCULAR_SURGERY = "Cirurgia Vascular",
  CLINICAL_PATHOLOGY = "Patologia Clínica",
  COLOPROCTOLOGY = "Coloproctologia",
  DERMATOLOGY = "Dermatologia",
  ENDOCRINOLOGY = "Endocrinologia",
  ENDOSCOPY = "Endoscopia",
  FAMILY_MEDICINE = "Medicina de Família",
  GASTROENTEROLOGY = "Gastroenterologia",
  GENERAL_PRACTITIONER = "Clínica Geral",
  GERIATRICS = "Geriatria",
  GYNECOLOGY_OBSTETRICS = "Ginecologia e Obstetrícia",
  HEMATOLOGY = "Hematologia",
  INFECTIOUS_DISEASE = "Infectologia",
  INTENSIVE_CARE = "Medicina Intensiva",
  INTERNAL_MEDICINE = "Medicina Interna",
  MASTOLOGY = "Mastologia",
  MEDICAL_GENETICS = "Genética Médica",
  NEPHROLOGY = "Nefrologia",
  NEUROLOGY = "Neurologia",
  NEUROSURGERY = "Neurocirurgia",
  NUCLEAR_MEDICINE = "Medicina Nuclear",
  OCCUPATIONAL_MEDICINE = "Medicina do Trabalho",
  ONCOLOGY = "Oncologia",
  OPHTHALMOLOGY = "Oftalmologia",
  ORTHOPEDICS = "Ortopedia",
  OTOLARYNGOLOGY = "Otorrinolaringologia",
  PATHOLOGY = "Patologia",
  PEDIATRICS = "Pediatria",
  PHYSICAL_MEDICINE = "Medicina Física e Reabilitação",
  PNEUMOLOGY = "Pneumologia",
  PSYCHIATRY = "Psiquiatria",
  RADIOLOGY = "Radiologia",
  RHEUMATOLOGY = "Reumatologia",
  SPORTS_MEDICINE = "Medicina Esportiva",
  UROLOGY = "Urologia",
}

export const DoctorSpecialties = Object.entries(DoctorSpecialty).map(
  ([key, value]) => ({
    value: DoctorSpecialty[key as keyof typeof DoctorSpecialty],
    label: value,
  }),
);
